### ISSUE TITLE
crash in `VarType::Float` value debug builds on `misaligned pointer dereference`

### ISSUE THREAD

**Issue by harryhaaren** [superfell/iracing-telem#1]
Hi! First of all, thanks for sharing this library & code, its cool, and has been working well so far!

Having just updated compilers & chain, I'm now seeing that `debug` builds are causing "misaligned pointer load" warnings. This is likely that iRacing is not providing "natural alignment" of variables (e.g. f32 has to be 4-byte aligned, as it is 4 bytes in size). The exact _runtime_ panic I'm getting is this:
```
thread '<unnamed>' panicked at C:\Users\Me\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iracing-telem-0.2.0\src\lib.rs:303:48:
misaligned pointer dereference: address must be a multiple of 0x4 but is 0x19fc6ffbad9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 
https://github.com/superfell/iracing-telem/blob/eba045dc9f90d2ec5f69e25d2d10efb1b3d2b58a/src/lib.rs#L303

As we can see, line 303 is in an unsafe block, and does a cast of `x` to a `*const f32` value. Although unaligned loads are _fine_ on almost all modern CPUs, Rust in its wise-ness apparently checks for unaligned loads in debug builds. ( `--release` builds are fine!)

I think that a "more correct" solution from Rust-debug-builds would include a [read_unaligned](https://doc.rust-lang.org/std/ptr/fn.read_unaligned.html) indicating to the compiler to expect that this data *might* be mis-aligned. As a result, certain architectures might issue a different `load` assembly instruction to perform that load.

Likely that the other "single variable" types need similar treatment (this range):
https://github.com/superfell/iracing-telem/blob/eba045dc9f90d2ec5f69e25d2d10efb1b3d2b58a/src/lib.rs#L299-L304

I'm happy to file a PR with this change if that's helpful?

**Comment by superfell** [comment]
It's great to see someone else using this, thanks for the very detailed bug report! A PR would be great, thank you.

**Comment by harryhaaren** [comment]
As you've probably been notified, merging the PR linked above will resolve this issue.
